config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :messages_truck_available_calendars

  resources :truck_calendars

  resources :messages_staff_available_calendars

  resources :messages_task_calendars
  resources :staff_availables
  resources :messages_truck_calendars
  resources :subject_suggestions
  resources :truck_availables
  resources :email_alerts
  resources :payment_alerts
  resources :packing_alerts
  resources :equipment_alerts
  resources :time_alerts
  resources :access_alerts
  resources :cargo_alerts
  resources :move_source_alerts
  resources :move_keywords
  resources :move_webpages
  resources :move_referrals
  resources :move_sources
  resources :accounts
  resources :users
  resources :sessions
  resources :trucks
  resources :cities
  resources :city_locales
  resources :cargo_types
  resources :truck_sizes
  resources :move_types
  resources :clients
  resources :locations
  resources :move_records
  resources :taxes
  resources :config_parameters
  resources :profiles
  resources :calendar
  resources :calendar_tasks
  resources :calendar_truck_groups
  resources :calendar_staff_groups
  resources :subtask_staff_groups
  resources :personal_calendars
  resources :messages
  resources :roles
  resources :high_scores
  resources :messages_tasks
  resources :messages_move_records
  resources :reports
  resources :lead_report
  resources :customer
  resources :movers
  resources :move_type_alerts
  resources :contact_stages
  resources :customer_move_records

  get 'errors/file_not_found' => 'errors#file_not_found'
  get 'errors/unprocessable' => 'errors#unprocessable'
  get 'errors/internal_server_error' => 'errors#internal_server_error'
  get 'errors/unauthorized' => 'errors#unauthorized'
  post 'errors/unauthorized' => 'errors#unauthorized'
  delete 'errors/unauthorized' => 'errors#unauthorized'

  root 'sessions#index'

  post 'trucks/:id/upload_files/new' => 'image_trucks#create'
  delete 'trucks/:id/upload_files/destroy' => 'image_trucks#destroy'

  get 'home' => 'home#index'
  get 'forgot_password' => 'sessions#forgot_password'
  post 'forgot_password' => 'sessions#send_password_email'

  match '/login' => 'sessions#index', via: [:get, :post]
  get '/logout' => 'sessions#destroy'

  post 'edit_user_commissions/:id' => 'users#update_commission'

  post 'edit_commissions' => 'profiles#update_commission'
  get 'change_password' => 'profiles#change_password'

  get 'action_roles' => 'action_roles#index'
  get 'action_roles/get_actions' => 'action_roles#get_actions'
  post 'action_roles/new' => 'action_roles#create'
  delete 'action_roles/remove' => 'action_roles#destroy'

  get 'action_users' => 'action_users#index'
  get 'action_users/get_actions' => 'action_users#get_actions'
  post 'action_users/new' => 'action_users#create'
  delete 'action_users/remove' => 'action_users#destroy'

  post 'accounts/upload_files/new' => 'image_account#create'
  delete 'accounts/upload_files/destroy' => 'image_account#destroy'
  get 'list_accounts' => 'accounts#list'
  get 'accounts/:id/edit' => 'accounts#edit'
  post 'accounts/new' => 'accounts#create'
  post 'users/new' => 'users#create_by_account'
  patch 'accounts/:id/edit' => 'accounts#update_by_id'
  get 'fill_table_accounts_list' => 'accounts#fill_table_account_list'

  post 'upload_files/new' => 'image_profile#create'
  delete 'upload_files/destroy' => 'image_profile#destroy'

  get 'calendar_movers' => 'calendar#move_calendar_event'
  get 'truck_calendar_resources' => 'calendar#truck_calendar_resources'
  put 'update_time_calendar_movers' => 'calendar#move_calendar_update_time'
  put 'update_day_calendar_movers' => 'calendar#move_calendar_update_day'
  put 'update_add_man_movers' => 'calendar#move_calendar_update_add_man'
  get 'information_staff_truck' => 'calendar#staff_man_truck_by_move_record'
  post 'add_reminder_calendar_mover' => 'calendar#add_reminder_calendar_mover'
  delete 'destroy_reminder_calendar_mover' => 'calendar#destroy_reminder_calendar_mover'
  post 'add_truck_move_record' => 'calendar#move_calendar_select_truck'
  post 'add_truck_clone' => 'calendar#move_calendar_clone_move'

  get 'calendar_task' => 'calendar_tasks#task_calendar_event'
  post 'add_subtask_group' => 'subtask_staff_groups#add_subtask_group'
  get 'task_calendar_resources' => 'calendar_tasks#task_calendar_resources'
  post 'add_staff_calendar_task' => 'calendar_tasks#add_staff_calendar_task'
  put 'update_day_calendar_tasks' => 'calendar_tasks#task_calendar_update_day'
  put 'update_time_calendar_tasks' => 'calendar_tasks#task_calendar_update_time'
  put 'update_task_information' => 'calendar_tasks#task_calendar_update_information'
  post 'add_reminder_calendar_task' => 'calendar_tasks#add_reminder_calendar_task'
  delete 'destroy_reminder_calendar_task' => 'calendar_tasks#destroy_reminder_calendar_task'
  delete 'destroy_staff_calendar_task' => 'calendar_tasks#destroy_staff_calendar_task'

  get 'calendar_personal' => 'personal_calendars#personal_calendar_event'
  post 'add_reminder_calendar_personal' => 'personal_calendars#add_reminder_calendar_personal'
  delete 'destroy_reminder_calendar_personal' => 'personal_calendars#destroy_reminder_calendar_personal'

  get 'calendar_truck' => 'truck_calendars#truck_calendar_event'
  post 'add_reminder_truck_calendar' => 'truck_calendars#add_reminder_truck_calendar'

  get 'contract_settings' => 'move_record_contract_settings#index'
  put 'contract_settings' => 'move_record_contract_settings#update'

  put 'update_readed_message' => 'messages#update_readed_message'
  delete 'destroy_message' => 'messages#destroy_message'
  post 'add_reply_message' => 'messages#add_reply_message'
  put 'mark_message' => 'messages#mark_message'

  put 'update_readed_message_task' => 'messages_tasks#update_readed_message'
  delete 'destroy_message_task' => 'messages_tasks#destroy_message'
  post 'add_reply_message_task' => 'messages_tasks#add_reply_message'
  put 'mark_message_task' => 'messages_tasks#mark_message'

  put 'update_readed_message_move_record' => 'messages_move_records#update_readed_message'
  delete 'destroy_message_move_record' => 'messages_move_records#destroy_message'
  post 'add_reply_message_move_record' => 'messages_move_records#add_reply_message'

  get 'update_messages_truck_calendar' => 'messages_truck_calendars#index_messages'

  get 'update_messages_task_calendar' => 'messages_task_calendars#index_messages'

  get 'commission_staff' => 'move_records#commission_by_staff'

  get 'fill_table_post_report' => 'reports#fill_table_post_report'
  get 'post_reports' => 'reports#view_post'
  get 'fill_table_source_report' => 'reports#fill_table_source_report'
  get 'source_reports' => 'reports#view_source'
  get 'fill_table_card_batch_report' => 'reports#fill_table_card_batch_report'
  get 'card_batch_reports' => 'reports#view_card_batch'

  get 'client_information' => 'clients#client_information'

  get 'fill_table_lead_report' => 'move_sections#fill_table_lead_report'
  get 'lead_reports' => 'move_sections#view_lead'
  get 'fill_table_quote_report' => 'move_sections#fill_table_quote_report'
  get 'quote_reports' => 'move_sections#view_quote'
  get 'fill_table_book_report' => 'move_sections#fill_table_book_report'
  get 'book_reports' => 'move_sections#view_book'
  get 'fill_table_dispatch_report' => 'move_sections#fill_table_dispatch_report'
  get 'dispatch_reports' => 'move_sections#view_dispatch'
  get 'fill_table_complete_report' => 'move_sections#fill_table_complete_report'
  get 'complete_reports' => 'move_sections#view_complete'

  get 'fill_table_list_move_record' => 'customer#fill_table_list_move_record'
  get 'fill_table_list_move_record_mover' => 'movers#fill_table_list_move_record_mover'

  get 'fill_table_move_lead' => 'personal_pages#fill_table_move_lead'
  get 'move_lead' => 'personal_pages#view_lead'
  get 'fill_table_move_quote' => 'personal_pages#fill_table_move_quote'
  get 'move_quote' => 'personal_pages#view_quote'
  get 'fill_table_move_book' => 'personal_pages#fill_table_move_book'
  get 'move_book' => 'personal_pages#view_book'
  get 'fill_table_complete_book' => 'personal_pages#fill_table_complete_book'
  get 'move_complete' => 'personal_pages#view_complete'
  get 'review_responses' => 'personal_pages#view_review_responses'

  get 'fill_table_statement' => 'statement#fill_table_statement'
  get 'statement' => 'statement#view_statement'

  get 'search_move_record' => 'search#index'

  get 'furnishings_information' => 'move_records#furnishings_information'
  get 'cargo_template_information' => 'move_records#cargo_template_information'

  get 'stats' => 'stats#view_stats'
  get 'fill_table_stats' => 'stats#fill_table_stats'

  put 'update_contact_stages' => 'move_records#update_contact_stages'
  get 'template_email' => 'email_alerts#template_email'
  get 'public_info/:id' => 'api_processes#public_info'
  post 'messages_move_records_public' => 'api_processes#create_message_move_record_public'
  get 'send_review_request' => 'move_records#send_review_request'
  get 'send_review_request2' => 'move_records#send_review_request2'
  get 'send_review_thank_you' => 'move_records#send_review_thank_you'
  get 'send_complaint_response' => 'move_records#send_complaint_response'
  get 'send_confirmation' => 'move_records#send_confirmation'
  get 'get_subsource_by_source' => 'move_records#get_subsource_by_source'

  scope "/api/v1" do
    post 'move_records' => 'api_processes#create_external_move_record'
    post 'replicate_old_system_move' => 'api_processes#replicate_old_system_move'
  end

  get 'terms' => 'pdf_process#terms'
  get 'cargo' => 'pdf_process#cargo'
  get 'cc_consent' => 'pdf_process#cc_consent'
  get 'damage_claim' => 'pdf_process#damage_claim'
  get 'move' => 'pdf_process#move'
  get 'non_disclosure' => 'pdf_process#non_disclosure'
  get 'costs_and_surchage' => 'pdf_process#costs_and_surchage'

  get 'cc_consent_mail' => 'mail_process#cc_consent'

app/models/calendar_truck_group.rb
class CalendarTruckGroup < ActiveRecord::Base
  attr_accessor :trucks
  after_commit :clear_cache

  has_many :review_links, dependent: :destroy
  has_one :tax, dependent: :destroy

  validates_presence_of :name

  private
  def clear_cache
    Rails.cache.delete("all_calendar_truck_group/#{self.account_id}")
  end
end

app/controllers/calendar_truck_groups_controller.rb
class CalendarTruckGroupsController < ApplicationController
  before_filter :current_user
  before_action :set_CalendarTruckGroup, only: [:edit, :update, :destroy]

  def index
    @calendar_truck_groups = CalendarTruckGroup.where(account_id: @current_user.account_id)
  end

  def new
    validate_permissions("create_edit.truck_calendars") ? '' : return
    @calendar_truck_group = CalendarTruckGroup.new
    @calendar_truck_group.trucks = {}
    @trucks = Truck.joins('left join list_truck_groups on trucks.id = list_truck_groups.truck_id').where(account_id: @current_user.account_id, active: 1).where('list_truck_groups.truck_id' => nil)

    @gst = "0.00"
    @pst = "0.00"

    @provinces = Province.order(description: :asc)
    @cities = []
    @current_city = City.new
    @locales = []
    @current_locale = CityLocale.new
  end

  def create
    validate_permissions("create_edit.truck_calendars") ? '' : return
    @calendar_truck_group = CalendarTruckGroup.new(calendar_truck_group_params)
    @calendar_truck_group.account_id = @current_user.account_id
    respond_to do |format|
      if @calendar_truck_group.save
        fill_list_truck()
        taxes = Tax.find_or_create_by(calendar_truck_group_id: @calendar_truck_group.id, account_id: @current_user.account_id)
        taxes.gst = params[:gst]
        taxes.pst = params[:pst]
        taxes.save

        format.html { redirect_to calendar_truck_groups_url }
        format.json { render :index }
      else
        format.html { render :new }
        format.json { render json: @calendar_truck_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    validate_permissions("create_edit.truck_calendars") ? '' : return
    @calendar_truck_group.trucks = ListTruckGroup.where(account_id: @current_user.account_id, calendar_truck_group_id: @calendar_truck_group.id)
    @list_truck_group = []
    @trucks = Truck.joins('left join list_truck_groups on trucks.id = list_truck_groups.truck_id')
                  .where(account_id: @current_user.account_id, active: 1)
                  .where('list_truck_groups.truck_id IS NULL OR trucks.id in (?)', @calendar_truck_group.trucks.map { |v| v.truck_id.to_i })
    @calendar_truck_group.trucks.each do |truck|
      @list_truck_group.push(truck.truck_id)
    end
    tax = @calendar_truck_group.tax
    if tax
      @gst = tax.gst
      @pst = tax.pst
    else
      @gst = "0.00"
      @pst = "0.00"
    end


    @provinces = Province.order(description: :asc)
    @cities = City.where(province_id: @calendar_truck_group.province_id).order(description: :asc)
    @locales = CityLocale.where(city_id: @calendar_truck_group.city_id).order(locale_name: :asc)

    @review_link = ReviewLink.new
  end

  def update
    validate_permissions("create_edit.truck_calendars") ? '' : return
    fill_list_truck()
    respond_to do |format|
      if @calendar_truck_group.update(calendar_truck_group_params)
        taxes = Tax.find_or_create_by(calendar_truck_group_id: @calendar_truck_group.id, account_id: @current_user.account_id)
        taxes.gst = params[:gst]
        taxes.pst = params[:pst]
        taxes.save

        format.html { redirect_to calendar_truck_groups_url }
        format.json { render :index }
      else
        format.html { render :edit }
        format.json { render json: @calendar_truck_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    validate_permissions("create_edit.truck_calendars") ? '' : return
    @list_group = ListTruckGroup.find_by_calendar_truck_group_id(@calendar_truck_group.id)
    @list_group.destroy if not @list_group.nil?
    @calendar_truck_group.destroy
    respond_to do |format|
      format.html { redirect_to calendar_truck_groups_url, notice: 'Truck group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fill_list_truck
    ListTruckGroup.destroy_all(account_id: @current_user.account_id, calendar_truck_group_id: @calendar_truck_group.id)
    calendar_truck_group_params[:trucks].each do |truck|
      if (truck.present?)
        list_truck = ListTruckGroup.new
        list_truck.account_id = @current_user.account_id
        list_truck.truck_id = truck
        list_truck.calendar_truck_group_id = @calendar_truck_group.id
        list_truck.save
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_CalendarTruckGroup
    @calendar_truck_group = CalendarTruckGroup.find_by_id_and_account_id(params[:id], @current_user.account_id)
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def calendar_truck_group_params
    params.require(:calendar_truck_group).permit(:name, :phone_number, :description, :active, :address, :province_id, :city_id, :locale_id, :trucks => [])
  end
end

app/views/calendar_truck_groups/_form.html.erb
<%= form_for(@calendar_truck_group) do |f| %>
    <% if @calendar_truck_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@calendar_truck_group.errors.count, "error") %> prohibited this truck group from being
            saved:</h2>

          <ul>
            <% @calendar_truck_group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group col50 colmr">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="form-group col50-2">
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_field :description, class: 'form-control', required: true %>
    </div>

    <label>Taxes</label><br>
    <div class="form-group col1 colmr">
      <div class="p10" style="padding-left: 0px !important;">
        GST/HST <input class="form-control form-control2" step="0.01" type="number" value="<%= @gst %>" name="gst">
      </div>
    </div>

    <div class="form-group col1 colmr">
      <div class="p10">
        PST <input class="form-control form-control2" step="0.01" type="number" value="<%= @pst %>" name="pst">
      </div>
    </div>

    <div class="form-group clearfix">
      <%= f.label :active %><br>
      <%= f.check_box :active %>
    </div>
    <br/>

    <div class="form-group truck-profile-form">
      <%= f.label :trucks, 'Assing trucks' %><br>
      <%= f.collection_select :trucks, @trucks, :id, :description, {include_blank: true, :selected => @list_truck_group}, class: 'form-control multi-select-calendar-trucks', multiple: true, 'data-placeholder' => 'Select a truck', style: 'visibility: hidden;' %>
    </div>
    <br/>

    <!--
    <div class="form-group ptop5">
      <label>Province</label><br>
      <select class="form-control" id="sprovinces" name="calendar_truck_group[province_id]" required>
        <option></option>
        <% @provinces.each do |province| %>
            <option value="<%= province.id %>" <% if province.id == @calendar_truck_group.province_id %>selected<% end %>><%= province.description %></option>
        <% end %>
      </select>
    </div>

    <div class="form-group ptop5">
      <label>City</label><br>
      <select class="form-control" id="scities" name="calendar_truck_group[city_id]" required>
        <option></option>
        <% @cities.each do |city| %>
            <option value="<%= city.id %>" <% if city.id == @calendar_truck_group.city_id %>selected<% end %>><%= city.description %></option>
        <% end %>
      </select>
    </div>

    <div class="form-group ptop5">
      <a href="#" class="pull-right" onclick="show_locale_modal()">+ add new locale</a>
      <label>Locale</label><br>
      <select class="form-control" id="slocales" name="calendar_truck_group[locale_id]">
        <option></option>
        <% @locales.each do |locale| %>
            <option value="<%= locale.id %>" <% if locale.id == @calendar_truck_group.locale_id %>selected<% end %>><%= locale.locale_name %></option>
        <% end %>
      </select>
    </div>
    -->

    <div class="form-group">
      <br/>
      <button type="submit" name="commit" class="btn btn-primary">Save</button>
      <%= link_to 'Back', calendar_truck_groups_path, class: 'btn btn-primary' %>
    </div>
    <input type="hidden" id="hcalendar_city_id" value="<%= @calendar_truck_group.city_id %>">
    <input type="hidden" id="hcalendar_locale_id" value="<%= @calendar_truck_group.locale_id %>">
<% end %>

<!-- Locale Modal -->
<div class="modal fade" id="localeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form onsubmit="event.preventDefault()">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add new locale</h4>

        </div>
        <div class="modal-body">

          <div class="form-group">
            <label for="locale" class="control-label">Locale</label>
            <input type="text" class="form-control" id="locale_name" name="city_locale[locale_name]" required>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="saveLocale">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/calendar_truck_groups/edit.html.erb
<% @page_title = raw("<i class='icon-calendar blank3 blue-text brown'></i>") + "Truck Calendars" %>
<div class="body_top_margin col-md-12">
  <legend>Truck Group Calendar</legend>
  <%= render 'form' %>

  <br class="clearfix"><br>
  <legend>Review Links</legend>
  <div class="alert alert-inf text-big" role="alert">Review links are used for move review emails and for clients to rate and leave feedback in outside links you provide. For example, it can be social network link like your Facebook profile or Google profile. Clients can leave their reviews and rating that can increase your visibility to new potential clients. <span class="green">Positive</span> and <span class="red">Negative feedback</span> will also be recorded on your moves with this truck group.</div>

  <div id="review_links" class="col-md-12">
    <% @calendar_truck_group.review_links.each do |link| %>
        <div class="pull-right">
          <%= link_to "Delete", review_link_path(id: link.id, calendar_truck_group_id: params[:id]), method: :delete, class: "btn", data: {confirm: "Are you sure?"}, id: "delete-btn" %>
        </div>
        <table width="36" cellspacing="0" cellpadding="0"><tr><td align="center">
        <p style="margin-bottom: 0px; margin-top: 5px;">
          <% if not link[:icon].nil? %>
            <a target="_blank" href="<%= link.link_url %>"><img src="/uploads/review_link/<%= link[:icon] %>" width="36"></a>
          <% end %>
        </p>
          <a target="_blank" href="<%= link.link_url %>" style="color: #000 !important;"><b style="font-size: 8pt"><%= link.name.html_safe %></b></a>
        </td></tr></table>
        <hr/>
    <% end %>
  </div>

  <a name="links"></a>
  <a class="no_underline big no_outline" href="javascript:void(0)" onclick="$('#add_review_link_modal').modal('show');"><i class="fa fa-plus small"></i> Add Review Link</a>
</div>

<br class="clearfix"><br>

<!-- Add Link Modal -->
<div class="modal fade" id="add_review_link_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for (@review_link), :html => {:class => 'form form-horizontal form-user-profile', multipart: true} do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Create New Review Link</h4>

        </div>
        <div class="modal-body">


            <div class="form-group2">
              <label for="image">Review Link Icon:</label>
              <%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png' %>
            </div>

            <div class="form-group2 mtop20">
              <label for="image">Review Link Name:</label>
              <%= f.text_field :name, class: 'form-control', required: true %>
            </div>

            <div class="form-group2 mtop20">
              <label for="image">Review Link URL:</label>
              <%= f.url_field :link_url, class: 'form-control', required: true, pattern: "https?://.+" %>
            </div>
            <%= f.hidden_field :calendar_truck_group_id, value: params[:id] %>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" id="save_review_link">Save</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  var topBar = document.getElementById("top-bar");

  topBar.innerHTML = '<div class="msg"><div class="top-bar-left-margin2"><div class="row '
      + '"><div class="text-left col-md-12">'
      + '<div class="pleft46 pright10">'

      + '<div class="colfl mright10">'
      + '<a href="<%= calendar_staff_groups_path %>" class="text-dark mtop6 no_underline fc-button fc-state-default fc-state-disabled pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text green"></i>Staff Calendars</a>'
      + '</div>'

      + '<div class="colfl mright10">'
      + '<a href="#" class="text-dark mtop6 no_underline fc-button fc-state-default no_pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text brown"></i>Truck Calendars</a>'
      + '</div>'

      + '</div>'
      + '</div></div></div></div>';
</script>

app/views/calendar_truck_groups/index.html.erb
<% @page_title = raw("<i class='icon-calendar blank3 blue-text brown'></i>") + "Truck Calendars" %>

<div class="col-md-12 body_top_margin">
  <div class="row">
    <div class="col-md-12">
      <% if validate_special_permission('create_edit.truck_calendars', @current_actions) %>
        <%= link_to 'New Truck Group Calendar', new_calendar_truck_group_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
  <br/>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-bordered table-hover">
        <tr>
          <th>Description</th>
          <th>Is Active?</th>
          <th>Actions</th>
        </tr>
        <% @calendar_truck_groups.each do |calendar_truck_group| %>
            <tr>
              <td><%= calendar_truck_group.description %></td>
              <td><%= check_box_tag 'active', calendar_truck_group.active, calendar_truck_group.active, disabled: true %></td>
              <td>
                <% if validate_special_permission('view.all_truck_calendars', @current_actions) %>
                  <%= link_to 'Show', calendar_index_path(type: 'trucks', group: calendar_truck_group.id) %>
                <% end %>
                <% if validate_special_permission('create_edit.truck_calendars', @current_actions) %>
                  <%= link_to 'Edit', edit_calendar_truck_group_path(calendar_truck_group) %>
                  <%= link_to 'Destroy', calendar_truck_group, method: :delete, data: {confirm: 'Are you sure?'} %>
                <% end %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<br class="clearfix"><br>

<script>
  var topBar = document.getElementById("top-bar");

  topBar.innerHTML = '<div class="msg"><div class="top-bar-left-margin2"><div class="row '
      + '"><div class="text-left col-md-12">'
      + '<div class="pleft46 pright10">'

      + '<div class="colfl mright10">'
      + '<a href="<%= calendar_staff_groups_path %>" class="text-dark mtop6 no_underline fc-button fc-state-default fc-state-disabled pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text green"></i>Staff Calendars</a>'
      + '</div>'

      + '<div class="colfl mright10">'
      + '<a href="#" class="text-dark mtop6 no_underline fc-button fc-state-default no_pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text brown"></i>Truck Calendars</a>'
      + '</div>'

      + '</div>'
      + '</div></div></div></div>';
</script>

app/views/calendar_truck_groups/new.html.erb
<% @page_title = raw("<i class='icon-calendar blank3 blue-text brown'></i>") + "Truck Calendars" %>
<div class="body_top_margin col-md-12">
  <legend>New Truck Group Calendar</legend>

  <%= render 'form' %>

</div>

<br class="clearfix"><br>

<script>
    var topBar = document.getElementById("top-bar");

    topBar.innerHTML = '<div class="msg"><div class="top-bar-left-margin2"><div class="row '
        + '"><div class="text-left col-md-12">'
        + '<div class="pleft46 pright10">'

        + '<div class="colfl mright10">'
        + '<a href="<%= calendar_staff_groups_path %>" class="text-dark mtop6 no_underline fc-button fc-state-default fc-state-disabled pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text green"></i>Staff Calendars</a>'
        + '</div>'

        + '<div class="colfl mright10">'
        + '<a href="#" class="text-dark mtop6 no_underline fc-button fc-state-default no_pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text brown"></i>Truck Calendars</a>'
        + '</div>'

        + '</div>'
        + '</div></div></div></div>';
</script>