config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :messages_truck_available_calendars

  resources :truck_calendars

  resources :messages_staff_available_calendars

  resources :messages_task_calendars
  resources :staff_availables
  resources :messages_truck_calendars
  resources :subject_suggestions
  resources :truck_availables
  resources :email_alerts
  resources :payment_alerts
  resources :packing_alerts
  resources :equipment_alerts
  resources :time_alerts
  resources :access_alerts
  resources :cargo_alerts
  resources :move_source_alerts
  resources :move_keywords
  resources :move_webpages
  resources :move_referrals
  resources :move_sources
  resources :accounts
  resources :users
  resources :sessions
  resources :trucks
  resources :cities
  resources :city_locales
  resources :cargo_types
  resources :truck_sizes
  resources :move_types
  resources :clients
  resources :locations
  resources :move_records
  resources :taxes
  resources :config_parameters
  resources :profiles
  resources :calendar
  resources :calendar_tasks
  resources :calendar_truck_groups
  resources :calendar_staff_groups
  resources :subtask_staff_groups
  resources :personal_calendars
  resources :messages
  resources :roles
  resources :high_scores
  resources :messages_tasks
  resources :messages_move_records
  resources :reports
  resources :lead_report
  resources :customer
  resources :movers
  resources :move_type_alerts
  resources :contact_stages
  resources :customer_move_records

  get 'errors/file_not_found' => 'errors#file_not_found'
  get 'errors/unprocessable' => 'errors#unprocessable'
  get 'errors/internal_server_error' => 'errors#internal_server_error'
  get 'errors/unauthorized' => 'errors#unauthorized'
  post 'errors/unauthorized' => 'errors#unauthorized'
  delete 'errors/unauthorized' => 'errors#unauthorized'

  root 'sessions#index'

  post 'trucks/:id/upload_files/new' => 'image_trucks#create'
  delete 'trucks/:id/upload_files/destroy' => 'image_trucks#destroy'

  get 'home' => 'home#index'
  get 'forgot_password' => 'sessions#forgot_password'
  post 'forgot_password' => 'sessions#send_password_email'

  match '/login' => 'sessions#index', via: [:get, :post]
  get '/logout' => 'sessions#destroy'

  post 'edit_user_commissions/:id' => 'users#update_commission'

  post 'edit_commissions' => 'profiles#update_commission'
  get 'change_password' => 'profiles#change_password'

  get 'action_roles' => 'action_roles#index'
  get 'action_roles/get_actions' => 'action_roles#get_actions'
  post 'action_roles/new' => 'action_roles#create'
  delete 'action_roles/remove' => 'action_roles#destroy'

  get 'action_users' => 'action_users#index'
  get 'action_users/get_actions' => 'action_users#get_actions'
  post 'action_users/new' => 'action_users#create'
  delete 'action_users/remove' => 'action_users#destroy'

  post 'accounts/upload_files/new' => 'image_account#create'
  delete 'accounts/upload_files/destroy' => 'image_account#destroy'
  get 'list_accounts' => 'accounts#list'
  get 'accounts/:id/edit' => 'accounts#edit'
  post 'accounts/new' => 'accounts#create'
  post 'users/new' => 'users#create_by_account'
  patch 'accounts/:id/edit' => 'accounts#update_by_id'
  get 'fill_table_accounts_list' => 'accounts#fill_table_account_list'

  post 'upload_files/new' => 'image_profile#create'
  delete 'upload_files/destroy' => 'image_profile#destroy'

  get 'calendar_movers' => 'calendar#move_calendar_event'
  get 'truck_calendar_resources' => 'calendar#truck_calendar_resources'
  put 'update_time_calendar_movers' => 'calendar#move_calendar_update_time'
  put 'update_day_calendar_movers' => 'calendar#move_calendar_update_day'
  put 'update_add_man_movers' => 'calendar#move_calendar_update_add_man'
  get 'information_staff_truck' => 'calendar#staff_man_truck_by_move_record'
  post 'add_reminder_calendar_mover' => 'calendar#add_reminder_calendar_mover'
  delete 'destroy_reminder_calendar_mover' => 'calendar#destroy_reminder_calendar_mover'
  post 'add_truck_move_record' => 'calendar#move_calendar_select_truck'
  post 'add_truck_clone' => 'calendar#move_calendar_clone_move'

  get 'calendar_task' => 'calendar_tasks#task_calendar_event'
  post 'add_subtask_group' => 'subtask_staff_groups#add_subtask_group'
  get 'task_calendar_resources' => 'calendar_tasks#task_calendar_resources'
  post 'add_staff_calendar_task' => 'calendar_tasks#add_staff_calendar_task'
  put 'update_day_calendar_tasks' => 'calendar_tasks#task_calendar_update_day'
  put 'update_time_calendar_tasks' => 'calendar_tasks#task_calendar_update_time'
  put 'update_task_information' => 'calendar_tasks#task_calendar_update_information'
  post 'add_reminder_calendar_task' => 'calendar_tasks#add_reminder_calendar_task'
  delete 'destroy_reminder_calendar_task' => 'calendar_tasks#destroy_reminder_calendar_task'
  delete 'destroy_staff_calendar_task' => 'calendar_tasks#destroy_staff_calendar_task'

  get 'calendar_personal' => 'personal_calendars#personal_calendar_event'
  post 'add_reminder_calendar_personal' => 'personal_calendars#add_reminder_calendar_personal'
  delete 'destroy_reminder_calendar_personal' => 'personal_calendars#destroy_reminder_calendar_personal'

  get 'calendar_truck' => 'truck_calendars#truck_calendar_event'
  post 'add_reminder_truck_calendar' => 'truck_calendars#add_reminder_truck_calendar'

  get 'contract_settings' => 'move_record_contract_settings#index'
  put 'contract_settings' => 'move_record_contract_settings#update'

  put 'update_readed_message' => 'messages#update_readed_message'
  delete 'destroy_message' => 'messages#destroy_message'
  post 'add_reply_message' => 'messages#add_reply_message'
  put 'mark_message' => 'messages#mark_message'

  put 'update_readed_message_task' => 'messages_tasks#update_readed_message'
  delete 'destroy_message_task' => 'messages_tasks#destroy_message'
  post 'add_reply_message_task' => 'messages_tasks#add_reply_message'
  put 'mark_message_task' => 'messages_tasks#mark_message'

  put 'update_readed_message_move_record' => 'messages_move_records#update_readed_message'
  delete 'destroy_message_move_record' => 'messages_move_records#destroy_message'
  post 'add_reply_message_move_record' => 'messages_move_records#add_reply_message'

  get 'update_messages_truck_calendar' => 'messages_truck_calendars#index_messages'

  get 'update_messages_task_calendar' => 'messages_task_calendars#index_messages'

  get 'commission_staff' => 'move_records#commission_by_staff'

  get 'fill_table_post_report' => 'reports#fill_table_post_report'
  get 'post_reports' => 'reports#view_post'
  get 'fill_table_source_report' => 'reports#fill_table_source_report'
  get 'source_reports' => 'reports#view_source'
  get 'fill_table_card_batch_report' => 'reports#fill_table_card_batch_report'
  get 'card_batch_reports' => 'reports#view_card_batch'

  get 'client_information' => 'clients#client_information'

  get 'fill_table_lead_report' => 'move_sections#fill_table_lead_report'
  get 'lead_reports' => 'move_sections#view_lead'
  get 'fill_table_quote_report' => 'move_sections#fill_table_quote_report'
  get 'quote_reports' => 'move_sections#view_quote'
  get 'fill_table_book_report' => 'move_sections#fill_table_book_report'
  get 'book_reports' => 'move_sections#view_book'
  get 'fill_table_dispatch_report' => 'move_sections#fill_table_dispatch_report'
  get 'dispatch_reports' => 'move_sections#view_dispatch'
  get 'fill_table_complete_report' => 'move_sections#fill_table_complete_report'
  get 'complete_reports' => 'move_sections#view_complete'

  get 'fill_table_list_move_record' => 'customer#fill_table_list_move_record'
  get 'fill_table_list_move_record_mover' => 'movers#fill_table_list_move_record_mover'

  get 'fill_table_move_lead' => 'personal_pages#fill_table_move_lead'
  get 'move_lead' => 'personal_pages#view_lead'
  get 'fill_table_move_quote' => 'personal_pages#fill_table_move_quote'
  get 'move_quote' => 'personal_pages#view_quote'
  get 'fill_table_move_book' => 'personal_pages#fill_table_move_book'
  get 'move_book' => 'personal_pages#view_book'
  get 'fill_table_complete_book' => 'personal_pages#fill_table_complete_book'
  get 'move_complete' => 'personal_pages#view_complete'
  get 'review_responses' => 'personal_pages#view_review_responses'

  get 'fill_table_statement' => 'statement#fill_table_statement'
  get 'statement' => 'statement#view_statement'

  get 'search_move_record' => 'search#index'

  get 'furnishings_information' => 'move_records#furnishings_information'
  get 'cargo_template_information' => 'move_records#cargo_template_information'

  get 'stats' => 'stats#view_stats'
  get 'fill_table_stats' => 'stats#fill_table_stats'

  put 'update_contact_stages' => 'move_records#update_contact_stages'
  get 'template_email' => 'email_alerts#template_email'
  get 'public_info/:id' => 'api_processes#public_info'
  post 'messages_move_records_public' => 'api_processes#create_message_move_record_public'
  get 'send_review_request' => 'move_records#send_review_request'
  get 'send_review_request2' => 'move_records#send_review_request2'
  get 'send_review_thank_you' => 'move_records#send_review_thank_you'
  get 'send_complaint_response' => 'move_records#send_complaint_response'
  get 'send_confirmation' => 'move_records#send_confirmation'
  get 'get_subsource_by_source' => 'move_records#get_subsource_by_source'

  scope "/api/v1" do
    post 'move_records' => 'api_processes#create_external_move_record'
    post 'replicate_old_system_move' => 'api_processes#replicate_old_system_move'
  end

  get 'terms' => 'pdf_process#terms'
  get 'cargo' => 'pdf_process#cargo'
  get 'cc_consent' => 'pdf_process#cc_consent'
  get 'damage_claim' => 'pdf_process#damage_claim'
  get 'move' => 'pdf_process#move'
  get 'non_disclosure' => 'pdf_process#non_disclosure'
  get 'costs_and_surchage' => 'pdf_process#costs_and_surchage'

  get 'cc_consent_mail' => 'mail_process#cc_consent'

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include MessagesHelper
  before_filter :current_user

  def index
    @page_title = ("<i class='icon-dashboard blank3 blue-text'></i>" + "Dashboard").html_safe

    # My mail
    get_personal_messages()

    # Calendar
    @reminders = []

    reminder_personal = ReminderCalendarPersonal.where("DATE(date) BETWEEN ? AND ? AND account_id = ? ",
                                                       DateTime.now.midnight.to_s(:db),
                                                       DateTime.now.end_of_day.to_s(:db),
                                                       @current_user.account_id)
                            .where(user_id: @current_user.id)
                            .order(date: :desc)
    reminder_move = ReminderCalendarMoveRecord.where("DATE(date) BETWEEN ? AND ? AND account_id = ? ", DateTime.now.midnight.to_s(:db), DateTime.now.end_of_day.to_s(:db), @current_user.account_id)
                        .where("user_id=? OR user_id is null", @current_user.id).order(date: :desc)
    reminder_task = ReminderCalendarTask.where("DATE(date) BETWEEN ? AND ? AND account_id = ? ", DateTime.now.midnight.to_s(:db), DateTime.now.end_of_day.to_s(:db), @current_user.account_id)
                        .where("user_id=? OR user_id is null", @current_user.id).order(date: :desc)
    @reminders = reminder_personal + reminder_move + reminder_task
  end
end

app/views/home/index.html.erb
<div class="col-md-12 dashboard-home">
  <% if !flash[:notice].blank? %>
      <div class="row">
        <div class="col-md-12">
          <div class="alert alert-success alert-dismissable">
            <h4>
              <i class="icon-ok-sign"></i>
              Successful
            </h4>

            <p><%= flash[:notice] %></p>
          </div>
        </div>
      </div>
  <% end %>

  <%# if validate_special_permission('show.dashboard_my_mail', @current_actions) %>
      <br/>
      <div class="row colpd mtop5 no-pright">
        <div class="col7">
          <legend>
            <span onclick="location.href='<%= messages_path(type: 'inbox') %>'" class="pointer"><i class="icon-envelope" aria-hidden="true"></i> MY MAIL</span>
            <div class="pull-right">
              <a class="btn btn-xs btn-link no_underline expand-my-mail" href="javascript:void(0)" onclick="expand_my_mail()"><i class="fa fa-chevron-up"></i></a>
            </div>
          </legend>
        </div>
      </div>

      <div class="my-mail-section scrolled">
        <% if @full_messages.blank? %>
            <div class="row">
              <div class="col-md-12 ptop10 pbottom10 pleft25"> No messages available.</div>
            </div>
        <% else %>

            <div class="row">
              <div class="col-md-12">
                <div class="">
                  <div class="box_header p3 no-border-top">
                    <div class="col-md-1">
                      <span></span>
                    </div>
                    <div class="col-md-1">
                      <b class="text-black text-big">From</b>
                    </div>
                    <div class="col-md-8 row">
                      <div class="col-md-4">
                        <b class="text-black text-big">To</b>
                      </div>
                      <div class="col-md-4">
                        <b class="text-black text-big">Subject</b>
                      </div>
                      <div class="col-md-4">

                      </div>
                    </div>
                    <div class="col-md-2">
                      <a href="?message_sort=<%= (params[:message_sort].present? ? (params[:message_sort] == 'DESC' ? 'ASC' : 'DESC') : 'DESC') %>&type=inbox" class="underline-out"><span>Time/Date <i class="<%= (params[:message_sort].present? ? (params[:message_sort] == 'DESC' ? 'icon-caret-up' : 'icon-caret-down') : 'icon-caret-down') %>"></i> </span></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <%= render "messages/index", full_messages: @full_messages, type: 'inbox' %>
        <% end %>
      </div>
  <%# end %>

  <% if @roles and not @roles.include?("Customer") %>
      <br/>

      <div class="row colpd mtop15 no-pright">
        <div class="col7">
          <legend>
            <span onclick="location.href='<%= personal_calendars_path %>'" class="pointer"><i class='icon-calendar'></i> MY CALENDAR - <%= Date.today.strftime("%A %B %d %Y") %></span>
            <div class="pull-right">
              <a class="btn btn-xs btn-link no_underline expand-my-calendar" href="javascript:void(0)" onclick="expand_my_calendar()"><i class="fa fa-chevron-up"></i></a>
            </div>
          </legend>
        </div>
      </div>

      <div class="my-calendar-section">
        <div id="calendar-home">
        </div>
        <% content_for :special_js do %>
            <link href="/assets/template/plugins/fullcalendar-scheduler.css" media="all" rel="stylesheet">
            <link href="/assets/template/plugins/scheduler.css" media="all" rel="stylesheet">
            <script src="/assets/template/plugins/timelineview/fullcalendar-scheduler.min.js"></script>
            <script src="/assets/template/plugins/timelineview/scheduler.min.js"></script>
            <script src="/assets/home.js"></script>
        <% end %>
      </div>

  <% end %>

  <% if @roles and not @roles.include?("Customer") %>
      <br/>

      <div class="row colpd mtop15 no-pright">
        <div class="col7">
          <legend>
            <span onclick="location.href='<%= statement_path %>'" class="pointer"><i class='icon-file-text'></i> MY STATEMENTS</span>
            <div class="pull-right">
              <a class="btn btn-xs btn-link no_underline expand-my-statements" href="javascript:void(0)" onclick="expand_my_statements()"><i class="fa fa-chevron-up"></i></a>
            </div>
          </legend>
        </div>
      </div>

      <div class="my-statements-section">
        <div class="table-responsive">
          <div class="scrollable-area">
            <table class="data-table-column-filter-statement table table-bordered table-striped table-hover dataTable" style="margin-bottom:0; min-height: 110px;" id="DataTables_Table_report" aria-describedby="DataTables_Table_report_info" data-report="statement">
              <thead>
              <tr role="row">
                <th class="sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">
                  Name
                </th>
                <th role="columnheader" tabindex="0" rowspan="1" colspan="1">
                  Stages
                </th>
                <th class="sorting" role="columnheader" tabindex="0" rowspan="1" colspan="1">
                  Date
                </th>
                <th class="sorting" role="columnheader" tabindex="0" colspan="1">
                  Total earnings
                </th>
              </tr>
              </thead>
              <tfoot>
              <tr>
                <th rowspan="1" role="columnheader" tabindex="0" colspan="3" style="text-align:right">Total:</th>
                <th></th>
              </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
  <% end %>
  <br/><br/>
</div>