config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :messages_truck_available_calendars

  resources :truck_calendars

  resources :messages_staff_available_calendars

  resources :messages_task_calendars
  resources :staff_availables
  resources :messages_truck_calendars
  resources :subject_suggestions
  resources :truck_availables
  resources :email_alerts
  resources :payment_alerts
  resources :packing_alerts
  resources :equipment_alerts
  resources :time_alerts
  resources :access_alerts
  resources :cargo_alerts
  resources :move_source_alerts
  resources :move_keywords
  resources :move_webpages
  resources :move_referrals
  resources :move_sources
  resources :accounts
  resources :users
  resources :sessions
  resources :trucks
  resources :cities
  resources :city_locales
  resources :cargo_types
  resources :truck_sizes
  resources :move_types
  resources :clients
  resources :locations
  resources :move_records
  resources :taxes
  resources :config_parameters
  resources :profiles
  resources :calendar
  resources :calendar_tasks
  resources :calendar_truck_groups
  resources :calendar_staff_groups
  resources :subtask_staff_groups
  resources :personal_calendars
  resources :messages
  resources :roles
  resources :high_scores
  resources :messages_tasks
  resources :messages_move_records
  resources :reports
  resources :lead_report
  resources :customer
  resources :movers
  resources :move_type_alerts
  resources :contact_stages
  resources :customer_move_records

  get 'errors/file_not_found' => 'errors#file_not_found'
  get 'errors/unprocessable' => 'errors#unprocessable'
  get 'errors/internal_server_error' => 'errors#internal_server_error'
  get 'errors/unauthorized' => 'errors#unauthorized'
  post 'errors/unauthorized' => 'errors#unauthorized'
  delete 'errors/unauthorized' => 'errors#unauthorized'

  root 'sessions#index'

  post 'trucks/:id/upload_files/new' => 'image_trucks#create'
  delete 'trucks/:id/upload_files/destroy' => 'image_trucks#destroy'

  get 'home' => 'home#index'
  get 'forgot_password' => 'sessions#forgot_password'
  post 'forgot_password' => 'sessions#send_password_email'

  match '/login' => 'sessions#index', via: [:get, :post]
  get '/logout' => 'sessions#destroy'

  post 'edit_user_commissions/:id' => 'users#update_commission'

  post 'edit_commissions' => 'profiles#update_commission'
  get 'change_password' => 'profiles#change_password'

  get 'action_roles' => 'action_roles#index'
  get 'action_roles/get_actions' => 'action_roles#get_actions'
  post 'action_roles/new' => 'action_roles#create'
  delete 'action_roles/remove' => 'action_roles#destroy'

  get 'action_users' => 'action_users#index'
  get 'action_users/get_actions' => 'action_users#get_actions'
  post 'action_users/new' => 'action_users#create'
  delete 'action_users/remove' => 'action_users#destroy'

  post 'accounts/upload_files/new' => 'image_account#create'
  delete 'accounts/upload_files/destroy' => 'image_account#destroy'
  get 'list_accounts' => 'accounts#list'
  get 'accounts/:id/edit' => 'accounts#edit'
  post 'accounts/new' => 'accounts#create'
  post 'users/new' => 'users#create_by_account'
  patch 'accounts/:id/edit' => 'accounts#update_by_id'
  get 'fill_table_accounts_list' => 'accounts#fill_table_account_list'

  post 'upload_files/new' => 'image_profile#create'
  delete 'upload_files/destroy' => 'image_profile#destroy'

  get 'calendar_movers' => 'calendar#move_calendar_event'
  get 'truck_calendar_resources' => 'calendar#truck_calendar_resources'
  put 'update_time_calendar_movers' => 'calendar#move_calendar_update_time'
  put 'update_day_calendar_movers' => 'calendar#move_calendar_update_day'
  put 'update_add_man_movers' => 'calendar#move_calendar_update_add_man'
  get 'information_staff_truck' => 'calendar#staff_man_truck_by_move_record'
  post 'add_reminder_calendar_mover' => 'calendar#add_reminder_calendar_mover'
  delete 'destroy_reminder_calendar_mover' => 'calendar#destroy_reminder_calendar_mover'
  post 'add_truck_move_record' => 'calendar#move_calendar_select_truck'
  post 'add_truck_clone' => 'calendar#move_calendar_clone_move'

  get 'calendar_task' => 'calendar_tasks#task_calendar_event'
  post 'add_subtask_group' => 'subtask_staff_groups#add_subtask_group'
  get 'task_calendar_resources' => 'calendar_tasks#task_calendar_resources'
  post 'add_staff_calendar_task' => 'calendar_tasks#add_staff_calendar_task'
  put 'update_day_calendar_tasks' => 'calendar_tasks#task_calendar_update_day'
  put 'update_time_calendar_tasks' => 'calendar_tasks#task_calendar_update_time'
  put 'update_task_information' => 'calendar_tasks#task_calendar_update_information'
  post 'add_reminder_calendar_task' => 'calendar_tasks#add_reminder_calendar_task'
  delete 'destroy_reminder_calendar_task' => 'calendar_tasks#destroy_reminder_calendar_task'
  delete 'destroy_staff_calendar_task' => 'calendar_tasks#destroy_staff_calendar_task'

  get 'calendar_personal' => 'personal_calendars#personal_calendar_event'
  post 'add_reminder_calendar_personal' => 'personal_calendars#add_reminder_calendar_personal'
  delete 'destroy_reminder_calendar_personal' => 'personal_calendars#destroy_reminder_calendar_personal'

  get 'calendar_truck' => 'truck_calendars#truck_calendar_event'
  post 'add_reminder_truck_calendar' => 'truck_calendars#add_reminder_truck_calendar'

  get 'contract_settings' => 'move_record_contract_settings#index'
  put 'contract_settings' => 'move_record_contract_settings#update'

  put 'update_readed_message' => 'messages#update_readed_message'
  delete 'destroy_message' => 'messages#destroy_message'
  post 'add_reply_message' => 'messages#add_reply_message'
  put 'mark_message' => 'messages#mark_message'

  put 'update_readed_message_task' => 'messages_tasks#update_readed_message'
  delete 'destroy_message_task' => 'messages_tasks#destroy_message'
  post 'add_reply_message_task' => 'messages_tasks#add_reply_message'
  put 'mark_message_task' => 'messages_tasks#mark_message'

  put 'update_readed_message_move_record' => 'messages_move_records#update_readed_message'
  delete 'destroy_message_move_record' => 'messages_move_records#destroy_message'
  post 'add_reply_message_move_record' => 'messages_move_records#add_reply_message'

  get 'update_messages_truck_calendar' => 'messages_truck_calendars#index_messages'

  get 'update_messages_task_calendar' => 'messages_task_calendars#index_messages'

  get 'commission_staff' => 'move_records#commission_by_staff'

  get 'fill_table_post_report' => 'reports#fill_table_post_report'
  get 'post_reports' => 'reports#view_post'
  get 'fill_table_source_report' => 'reports#fill_table_source_report'
  get 'source_reports' => 'reports#view_source'
  get 'fill_table_card_batch_report' => 'reports#fill_table_card_batch_report'
  get 'card_batch_reports' => 'reports#view_card_batch'

  get 'client_information' => 'clients#client_information'

  get 'fill_table_lead_report' => 'move_sections#fill_table_lead_report'
  get 'lead_reports' => 'move_sections#view_lead'
  get 'fill_table_quote_report' => 'move_sections#fill_table_quote_report'
  get 'quote_reports' => 'move_sections#view_quote'
  get 'fill_table_book_report' => 'move_sections#fill_table_book_report'
  get 'book_reports' => 'move_sections#view_book'
  get 'fill_table_dispatch_report' => 'move_sections#fill_table_dispatch_report'
  get 'dispatch_reports' => 'move_sections#view_dispatch'
  get 'fill_table_complete_report' => 'move_sections#fill_table_complete_report'
  get 'complete_reports' => 'move_sections#view_complete'

  get 'fill_table_list_move_record' => 'customer#fill_table_list_move_record'
  get 'fill_table_list_move_record_mover' => 'movers#fill_table_list_move_record_mover'

  get 'fill_table_move_lead' => 'personal_pages#fill_table_move_lead'
  get 'move_lead' => 'personal_pages#view_lead'
  get 'fill_table_move_quote' => 'personal_pages#fill_table_move_quote'
  get 'move_quote' => 'personal_pages#view_quote'
  get 'fill_table_move_book' => 'personal_pages#fill_table_move_book'
  get 'move_book' => 'personal_pages#view_book'
  get 'fill_table_complete_book' => 'personal_pages#fill_table_complete_book'
  get 'move_complete' => 'personal_pages#view_complete'
  get 'review_responses' => 'personal_pages#view_review_responses'

  get 'fill_table_statement' => 'statement#fill_table_statement'
  get 'statement' => 'statement#view_statement'

  get 'search_move_record' => 'search#index'

  get 'furnishings_information' => 'move_records#furnishings_information'
  get 'cargo_template_information' => 'move_records#cargo_template_information'

  get 'stats' => 'stats#view_stats'
  get 'fill_table_stats' => 'stats#fill_table_stats'

  put 'update_contact_stages' => 'move_records#update_contact_stages'
  get 'template_email' => 'email_alerts#template_email'
  get 'public_info/:id' => 'api_processes#public_info'
  post 'messages_move_records_public' => 'api_processes#create_message_move_record_public'
  get 'send_review_request' => 'move_records#send_review_request'
  get 'send_review_request2' => 'move_records#send_review_request2'
  get 'send_review_thank_you' => 'move_records#send_review_thank_you'
  get 'send_complaint_response' => 'move_records#send_complaint_response'
  get 'send_confirmation' => 'move_records#send_confirmation'
  get 'get_subsource_by_source' => 'move_records#get_subsource_by_source'

  scope "/api/v1" do
    post 'move_records' => 'api_processes#create_external_move_record'
    post 'replicate_old_system_move' => 'api_processes#replicate_old_system_move'
  end

  get 'terms' => 'pdf_process#terms'
  get 'cargo' => 'pdf_process#cargo'
  get 'cc_consent' => 'pdf_process#cc_consent'
  get 'damage_claim' => 'pdf_process#damage_claim'
  get 'move' => 'pdf_process#move'
  get 'non_disclosure' => 'pdf_process#non_disclosure'
  get 'costs_and_surchage' => 'pdf_process#costs_and_surchage'

  get 'cc_consent_mail' => 'mail_process#cc_consent'

app/models/calendar_staff_group.rb
class CalendarStaffGroup < ActiveRecord::Base
  after_commit :clear_cache

  private
  def clear_cache
    Rails.cache.delete("all_calendar_staff_group/#{self.account_id}")
  end
end

app/controllers/calendar_staff_groups_controller.rb
class CalendarStaffGroupsController < ApplicationController
  before_filter :current_user
  before_action :set_CalendarStaffGroup, only: [:edit, :update, :destroy]

  def index
    @calendar_staff_groups = CalendarStaffGroup.where(account_id: @current_user.account_id)
  end

  def new
    validate_permissions("create_edit.staff_calendars") ? '' : return
    @calendar_staff_group = CalendarStaffGroup.new
  end

  def create
    validate_permissions("create_edit.staff_calendars") ? '' : return
    @calendar_staff_group = CalendarStaffGroup.new(calendar_staff_group_params)
    @calendar_staff_group.account_id = @current_user.account_id
    respond_to do |format|
      if @calendar_staff_group.save
        format.html { redirect_to "/calendar_staff_groups/#{@calendar_staff_group.id}/edit" }
        format.json { render :index }
      else
        format.html { render :new }
        format.json { render json: @calendar_staff_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    validate_permissions("create_edit.staff_calendars") ? '' : return
    @list_staff_group = []
    @subtasks = SubtaskStaffGroup.where(account_id: @current_user.account_id, calendar_staff_group_id: params[:id])
    @role = Role.new
    @existing_roles = Role.where(account_id: @current_user.account_id, calendar_staff_group_id: nil)
    @calendar_roles = Role.where(account_id: @current_user.account_id, calendar_staff_group_id: params[:id])
  end

  def update
    validate_permissions("create_edit.staff_calendars") ? '' : return
    respond_to do |format|
      if @calendar_staff_group.update(calendar_staff_group_params)
        format.html { redirect_to calendar_staff_groups_url }
        format.json { render :index }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @calendar_staff_group.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    validate_permissions("create_edit.staff_calendars") ? '' : return
    @calendar_staff_group.destroy
    respond_to do |format|
      format.html { redirect_to calendar_staff_groups_url }
      format.json { head :no_content }
      format.js { }
    end
  end

  def remove_role
    validate_permissions("create_edit.staff_calendars") ? '' : return
    role = Role.where(account_id: @current_user.account_id, id: params[:role_id])
    role.update(calendar_staff_group_id: nil)
    redirect_to :back
  end

  def assign_role
    validate_permissions("create_edit.staff_calendars") ? '' : return
    respond_to do |format|
      role = Role.where(account_id: @current_user.account_id, id: params[:role_id])
      if role.update(calendar_staff_group_id: params[:cal_id])
        format.json { render json: role }
      else
        format.json { render json: role.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_CalendarStaffGroup
    @calendar_staff_group = CalendarStaffGroup.find_by_id_and_account_id(params[:id], @current_user.account_id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def calendar_staff_group_params
    params.require(:calendar_staff_group).permit(:name, :description, :active, :users => [])
  end
end

app/views/calendar_staff_groups/_form.html.erb
<%= form_for(@calendar_staff_group) do |f| %>
    <% if @calendar_staff_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@calendar_staff_group.errors.count, "error") %> prohibited this truck group from being saved:</h2>
          <ul>
            <% @calendar_staff_group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_field :description, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :active %><br>
      <%= f.check_box :active %>
    </div>

    <br/>
    <div class="form-group">
      <button type="submit" name="commit" class="btn btn-primary">Save</button>
      <%= link_to 'Back', calendar_staff_groups_path, class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/calendar_staff_groups/destroy.js.erb
var user = $('.user-name').data('user');
var cal_id = <%= params[:id] %>;

localStorage.removeItem(user + '_taskcalendar_' + cal_id);

location.reload();

app/views/calendar_staff_groups/edit.html.erb
<% @page_title = raw("<i class='icon-calendar blank3 blue-text green'></i>") + "Staff Calendars" %>

<div class="col-md-12">
  <div class="row body_top_margin">
    <div class="col-md-12">
      <legend>Staff Calendar</legend>
    </div>
  </div>

  <%= form_for(@calendar_staff_group, remote: true) do |f| %>
      <input type="hidden" id="cal_id" value="<%= @calendar_staff_group.id %>">
      <% if @calendar_staff_group.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@calendar_staff_group.errors.count, "error") %> prohibited this truck group from being
              saved:</h2>

            <ul>
              <% @calendar_staff_group.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_field :description, class: 'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label :active %><br>
        <%= f.check_box :active %>
      </div>

      <!--
      <div class="form-group">
        <label>Add Subtask Group</label>

        <div class="form-inline add-subtask-group">
          <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control name-subtask-group" placeholder="Name">
          </div>
          <div class="form-group">
            <label>Description</label>
            <input type="text" class="form-control description-subtask-group" placeholder="Description">
          </div>
          <div class="form-group">
            <label>Active</label>
            <input type="checkbox" checked="checked" class="form-control active-subtask-group">
          </div>
          <div class="form-group">
            <label>Mailbox</label>
            <input type="checkbox" checked="checked" class="form-control mailbox-subtask-group">
          </div>
          <button type="submit" class="btn btn-default btn-add-subtask-group" data-taskgroup="<%= @calendar_staff_group.id %>">Add</button>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :name, 'List Subtasks' %><br>
        <ul>
          <% @subtasks.each do |subtask| %>
              <li>
                <%= link_to subtask.name, edit_subtask_staff_group_path(subtask) %>
              </li>
          <% end %>
        </ul>
      </div>
      -->

      <div class="row">
        <div class="col-md-12">
          <legend class="no-m-bottom">Add Roles</legend>
        </div>
      </div>

      <div class="row">
        <table class="col-md-12"><tr valign="top">
          <td class="border_right col-md-6">
            <div class="ptop10">
              <!--<a href="javascript:void(0)" onclick="$('#roleModal').modal('show')" class="pull-right ptop1"><b>+ Add New Role</b></a>-->
              <label><b>Current Calendar Roles</b></label>
              <br class="clear"/>
              <br/>

              <table id="cal_roles_table" class="table table-striped table-bordered table-hover" style="border-top: 1px solid #7287a1;">
                <tr>
                  <th>role name</th>
                  <th>role level</th>
                  <th class="col-md-2"></th>
                </tr>
                <% if not @calendar_roles.blank? %>
                  <% @calendar_roles.each do |role| %>
                    <tr bgcolor="white">
                      <td><a href="/roles/<%= role.id %>/edit"><%= role.name %></a></td>
                      <td><%= role.role_level %></td>
                      <td><a href="/remove_calendar_role?role_id=<%= role.id %>">remove</a></td>
                    </tr>
                  <% end %>
                <% else %>
                  <tr bgcolor="white" id="no_roles">
                    <td colspan="3"><em class="small">No current roles</em></td>
                  </tr>
                <% end %>
              </table>


            </div>
          </td>

          <td class="col-md-6">
            <div class="ptop10">
              <div class="pull-right"><label><b>Assign a Role to Calendar</b></label> <i style="font-size: 14px !important;" class="glyphicon glyphicon-info-sign" data-toggle="tooltip" data-placement="right" title="You can assign any of the existing roles to the current calendar"></i></div>
              <br class="clear"/>
              <br/>

              <table class="col-md-12"><tr>
              <td class="col-md-3" align="center">
                <button type="button" class="btn btn-primary" id="btn_assign_cal_role" data-calendar="<%= params[:id]%> ">&lt;&lt;</button>
              </td>
              <td class="col-md-9 no-pright">
                <select id="assigned_role" class="auto-height-width" size="10">
                  <% @existing_roles.each do |role| %>
                    <option class="text-right" value="<%= role.id %>"><%= role.name %> &nbsp;&nbsp; level: <%= role.role_level %></option>
                  <% end %>
                </select>
              </td>
              </tr></table>

            </div>
          </td>
        </tr></table>

      </div>

      <br/>
      <div class="form-group">
        <button type="submit" name="commit" class="btn btn-primary">Save</button>
        <%= link_to 'Back', calendar_staff_groups_path, class: 'btn btn-primary' %>
      </div>
  <% end %>

</div>

<!-- New Role Modal -->
<div class="modal fade" id="roleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add New Role</h4>

        </div>
        <div class="modal-body">

          <%= render 'roles/form', redirect_url: request.original_url, calendar_staff_group_id: params[:id], f_remote: false %>
        </div>

    </div>
  </div>
</div>

<br class="clearfix"><br>

<script>
  var topBar = document.getElementById("top-bar");

  topBar.innerHTML = '<div class="msg"><div class="top-bar-left-margin2"><div class="row '
      + '"><div class="text-left col-md-12">'
      + '<div class="pleft46 pright10">'

      + '<div class="colfl mright10">'
      + '<a href="#" class="text-dark mtop6 no_underline fc-button fc-state-default no_pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text green"></i>Staff Calendars</a>'
      + '</div>'

      + '<div class="colfl mright10">'
      + '<a href="<%= calendar_truck_groups_path %>" class="text-dark mtop6 no_underline fc-button fc-state-default fc-state-disabled pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text brown"></i>Truck Calendars</a>'
      + '</div>'

      + '</div>'
      + '</div></div></div></div>';
</script>

app/views/calendar_staff_groups/index.html.erb
<% @page_title = raw("<i class='icon-calendar blank3 blue-text green'></i>") + "Staff Calendars" %>

<div class="col-md-12">
  <div class="row body_top_margin">
    <div class="col-md-12">
      <% if validate_special_permission('create_edit.staff_calendars', @current_actions) %>
        <%= link_to 'New Staff Calendar', new_calendar_staff_group_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-bordered table-hover">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Is Active?</th>
          <th>Actions</th>
        </tr>
        <% @calendar_staff_groups.each do |calendar_staff_group| %>
            <tr>
              <td><%= calendar_staff_group.name %></td>
              <td><%= calendar_staff_group.description %></td>
              <td><%= check_box_tag 'active', calendar_staff_group.active, calendar_staff_group.active, disabled: true %></td>
              <td class="col-md-3 nowrap">
                <% if validate_special_permission('view.all_staff_calendars', @current_actions) %>
                  <%= link_to 'Show', calendar_tasks_path(type: 'task', group: calendar_staff_group.id) %>
                <% end %>
                <% if validate_special_permission('create_edit.staff_calendars', @current_actions) %>
                  <%= link_to 'Edit', edit_calendar_staff_group_path(calendar_staff_group) %>
                <% end %>
                <!-- <%= link_to 'Destroy', calendar_staff_group, method: :delete, remote: true, data: {confirm: 'Are you sure?'} %> -->
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

<br class="clearfix"><br>

<script>
  var topBar = document.getElementById("top-bar");

  topBar.innerHTML = '<div class="msg"><div class="top-bar-left-margin2"><div class="row '
      + '"><div class="text-left col-md-12">'
      + '<div class="pleft46 pright10">'

      + '<div class="colfl mright10">'
      + '<a href="#" class="text-dark mtop6 no_underline fc-button fc-state-default no_pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text green"></i>Staff Calendars</a>'
      + '</div>'

      + '<div class="colfl mright10">'
      + '<a href="<%= calendar_truck_groups_path %>" class="text-dark mtop6 no_underline fc-button fc-state-default fc-state-disabled pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text brown"></i>Truck Calendars</a>'
      + '</div>'

      + '</div>'
      + '</div></div></div></div>';
</script>

app/views/calendar_staff_groups/new.html.erb
<% @page_title = raw("<i class='icon-calendar blank3 blue-text green'></i>") + "Staff Calendars" %>
<div class="col-md-12">
  <div class="row body_top_margin">
    <div class="col-md-12">
      <legend>New Staff Calendar</legend>
    </div>
  </div>

  <%= render 'form' %>

</div>

<br class="clearfix"><br>

<script>
    var topBar = document.getElementById("top-bar");

    topBar.innerHTML = '<div class="msg"><div class="top-bar-left-margin2"><div class="row '
        + '"><div class="text-left col-md-12">'
        + '<div class="pleft46 pright10">'

        + '<div class="colfl mright10">'
        + '<a href="#" class="text-dark mtop6 no_underline fc-button fc-state-default no_pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text green"></i>Staff Calendars</a>'
        + '</div>'

        + '<div class="colfl mright10">'
        + '<a href="<%= calendar_truck_groups_path %>" class="text-dark mtop6 no_underline fc-button fc-state-default fc-state-disabled pointer fc-corner-left fc-corner-right"><i class="icon-calendar blank3 blue-text brown"></i>Truck Calendars</a>'
        + '</div>'

        + '</div>'
        + '</div></div></div></div>';
</script>

app/views/calendar_staff_groups/update.js.erb
<% if not params[:calendar_staff_group][:active] == "1" %>
var user = $('.user-name').data('user');
var cal_id = $('#cal_id').val();

localStorage.removeItem(user + '_taskcalendar_' + cal_id);
<% end %>

location.href = "/calendar_staff_groups";